language: php
sudo: false
notifications:
  email: false

php:
  - 7.0
  - 5.6

env:
  global:
    - PLUGIN=S3
    - KANBOARD_REPO=https://github.com/kanboard/kanboard.git
  matrix:
    - DB=sqlite
    - DB=mysql
    - DB=postgres

matrix:
  fast_finish: true

install:
  - git clone --depth 1 $KANBOARD_REPO
  - ln -s $TRAVIS_BUILD_DIR kanboard/plugins/$PLUGIN
  - echo $TRAVIS_BUILD_DIR

before_script:
  - echo $PWD
  - cd kanboard
  - phpenv config-add tests/php.ini
  - composer install
  - composer install -d plugins/$PLUGIN

script:
  - phpunit -c tests/units.$DB.xml plugins/$PLUGIN/Test/

before_deploy:
  - echo $TRAVIS_TAG
  - git -C plugins/$PLUGIN archive HEAD --prefix=${PLUGIN}/ --format=zip -o ${PLUGIN}-${TRAVIS_TAG}.zip

deploy:
  provider: releases
  skip_cleanup: true
  script: 
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$

