language: php
sudo: false
notifications:
  email: false
php:
- 7.0
- 5.6
env:
  global:
  - PLUGIN=S3
  - KANBOARD_REPO=https://github.com/kanboard/kanboard.git
  matrix:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
matrix:
  fast_finish: true
install:
- git clone --depth 1 $KANBOARD_REPO ../kanboard
- ln -s $TRAVIS_BUILD_DIR ../kanboard/plugins/$PLUGIN
before_script:
- cd ../kanboard
- phpenv config-add tests/php.ini
- composer install
- composer install -d plugins/$PLUGIN
script:
- phpunit -c tests/units.$DB.xml plugins/$PLUGIN/Test/
before_deploy:
- pushd plugins ; zip -r $TRAVIS_BUILD_DIR/${PLUGIN}-${TRAVIS_TAG}.zip ${PLUGIN} --include "${PLUGIN}/*.php" "${PLUGIN}/LICENSE" "${PLUGIN}/Locale/*" "${PLUGIN}/README.md" "${PLUGIN}/Template/*" "${PLUGIN}/vendor/*"; popd
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_ENCRYPTED_SECRET
  file: "$TRAVIS_BUILD_DIR/${PLUGIN}-${TRAVIS_TAG}.zip"
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
    branch: master

